apiVersion: v1
kind: Service
metadata:
  name: flask-test-service
spec:
  selector:
    app: flask-test-app
  ports:
    - protocol: "TCP"
      port: 6000
      targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pda-react-app
spec:
  selector:
    matchLabels:
      app: pda-react-app
  replicas: 5
  template:
    metadata:
      labels:
        app: pda-react-app
    spec:
      containers:
        - name: pda-react-app
          image: pda-react-app
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
