apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-deployment
  labels:
    app: react-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: react-server
  template:
    metadata:
      labels:
        app: react-server
    spec:
      containers:
      - name: react
        image: ryanangweihao/rang012_docker_repository:REACT_2
        ports:
        - containerPort: 8000
      imagePullSecrets:
      - name: regcred
