apiVersion: v1
kind: Service
metadata:
  name: react-service
spec:
  type: NodePort
  selector:
    app: react-server
  ports:
    - protocol: TCP
      port: 5000      
      targetPort: 8000
      nodePort: 31000
